In [1]:
import numpy as np

### 使用属性函数创建

In [8]:
np.bool_([0, 1, 2])

array([False,  True,  True])

In [9]:
np.int_([False,  True,  True])

array([0, 1, 1])

In [10]:
np.float_([0, 1, 2])

array([0., 1., 2.])

In [11]:
np.complex_([0, 1, 2])

array([0.+0.j, 1.+0.j, 2.+0.j])

### 使用array()/arange()/linspace()函数创建

In [13]:
np.array([0, 1, 2])

array([0, 1, 2])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(1, 9, 5)

array([1., 3., 5., 7., 9.])

### 使用reshape()函数更改维度

In [19]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 指定数组的数据类型

In [28]:
np.array([0, 1, 2], dtype=np.bool_)

array([False,  True,  True])

In [29]:
np.linspace(1, 9, 5, dtype=np.complex_)

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])

In [32]:
np.arange(3, dtype='f')

array([0., 1., 2.], dtype=float32)

### 更改数组的数据类型

In [33]:
z = np.arange(3, dtype=np.int64)
z

array([0, 1, 2], dtype=int64)

In [38]:
a = np.float32(z)
a

array([0., 1., 2.], dtype=float32)

In [45]:
a = np.bool_(z)
a

array([False,  True,  True])

In [43]:
#astype
z.astype(np.complex64)

array([0.+0.j, 1.+0.j, 2.+0.j], dtype=complex64)

In [47]:
# issubdtype
np.issubdtype(z.dtype, np.int64)

True

### 数组的属性

In [48]:
a = np.arange(15).reshape(3, 5)

In [49]:
a.ndim

2

In [50]:
a.shape

(3, 5)

In [51]:
a.size

15

In [52]:
a.dtype

dtype('int32')

In [53]:
a.itemsize

4

In [54]:
a.data

### 创建指定元素的数组

In [55]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.full((2, 3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [64]:
a = np.eye(3, 2, dtype=int, k=-1)
a

array([[0, 0],
       [1, 0],
       [0, 1]])

In [66]:
np.empty_like(a)

array([[ 2046896384,  1936020665],
       [ 1292919248,         597],
       [          0, -2147483648]])

### Random

In [100]:
# rand(d0, d1, …, dn)rand
np.random.rand(3,2)

array([[0.23347896, 0.55353729],
       [0.20120199, 0.41216146],
       [0.40183875, 0.6130772 ]])

In [99]:
# random_sample([size])/sample([size])/ranf([size])/random([size])
np.random.random_sample((3,2))

array([[0.58210958, 0.65235986],
       [0.9693898 , 0.43437238],
       [0.69119211, 0.06962953]])

In [68]:
# randn(d0, d1, …, dn)  Two-by-four array of samples from N(3, 6.25):
2.5 * np.random.randn(3, 2) + 3

array([[ 1.20808453,  3.6821187 ],
       [ 3.49529461, -0.64507968],
       [ 2.41698939,  1.67996553]])

In [92]:
# randint(low[, high, size, dtype])
np.random.randint(1,3)

2

In [104]:
np.random.randint(2, 5, size=10, dtype=np.int64)

array([2, 4, 4, 2, 3, 2, 3, 2, 2, 4], dtype=int64)

In [94]:
np.random.randint(2, size=(2,3))

array([[0, 1, 1],
       [0, 0, 0]])

In [127]:
np.random.choice(['a', 'b', 'c'])

'a'

In [116]:
# 参数p为概率，p里的数据之和应为1, 参数p的长度与参数a的长度需要一致, replace表示是否可以重用元素
np.random.choice(5, 3, replace=True, p=[0.01, 0.01, 0.96, 0.01, 0.01])

array([2, 2, 2], dtype=int64)

In [132]:
np.random.seed(0) #每次产生一样的随机数
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

### 数组的运算

In [133]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
# ravel
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [140]:
a = b<12
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
# a.T.dot(b)
np.dot(a.T, b)

array([[12, 15, 18, 21],
       [12, 15, 18, 21],
       [12, 15, 18, 21],
       [12, 15, 18, 21]])

In [142]:
a.sum(axis=0)

array([3, 3, 3, 3])

In [143]:
a.sum(axis=1)

array([4, 4, 4])

In [144]:
np.add(a,b)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
np.vstack((a,b))

array([[ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
np.hstack((a,b))

array([[ 1,  1,  1,  1,  0,  1,  2,  3],
       [ 1,  1,  1,  1,  4,  5,  6,  7],
       [ 1,  1,  1,  1,  8,  9, 10, 11]])

In [148]:
a = np.array([-1.7, 0.2, 1.5, 2.7])
np.floor(a)

array([-2.,  0.,  1.,  2.])